name: Publish image to Docker
on:
  [workflow_dispatch]

  jobs:
  publish_images: 
  runs-on:ubuntu-latest
  steps:
  - name: checkout
  uses:actions/checkout@v4
  - name: build image
  run: docker build 
  - name: push image to docker hub
  run:
  docker push rishabkumar7/devops-qr-code-backend :latest

